name: Daily claim
on:
  schedule:
    - cron: '0 14 * * *' # UTC Time

jobs:
    Daily:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              ref: ${{ github.event.pull_request.head.sha }}
              fetch-depth: 0
          - run: python main.py
            env:
              MAIL_JWD: ${{ secrets.MAIL_JWD }}
              PASS_JWD: ${{ secrets.PASS_JWD }}
              IsGit: 1
    
