name: Daily claim
on:
  schedule:
    - cron: '0 14 * * *' # <- Use UTC Time +0 , change your time here ( 14 is hour , 0 is minutes ) and use 24-hour format

jobs:
    Daily:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3        
          - name: Run HoneygainPot
            run: python main.py
            env:
              MAIL: ${{ secrets.MAIL }} # <- DO NOT enter your email here, it may leak your information
              PASS: ${{ secrets.PASS }} # <- DO NOT enter your password here, it may leak your information
              JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # <- DO NOT enter your JWT Token here, it may leak your information
              IsJWT: 1 # <- 0 = Use Mail and Pass ; 1 = Use Token (Default is 1)
    
